### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kingwangwang** [easterngarden/ExportAllFBX#2]
#include <fbxsdk.h>  fatal  error C1083: 无法打开包括文件: “fbxsdk.h”: No such file or directory

**Comment by easterngarden** [comment]
You need to download Autodesk FBX SDK from https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2020-0 and change project setting in accordance.

**Comment by kingwangwang** [comment]
您好！您的邮件已收到。我将在假期结束后，尽快给你回复。祝您生活愉快。BY WJC

**Comment by easterngarden** [comment]
see previous comments.
